import DataGrid from '@renderer/components/DataGrid/DataGrid';
import { ColumnDef } from '@tanstack/react-table';

export default function Traffic() {
  return (
    <div className="bg-white">
      <DataGrid columns={columns} data={sampleData} />
    </div>
  );
}

// Sample columns definition
export const columns: ColumnDef<any> = [
  {
    accessorKey: 'id',
    header: 'ID',
    size: 600,
    maxSize: 600,
    enableResizing: true,
  },
  {
    accessorKey: 'firstName',
    header: 'First Name',
    enableResizing: true,
  },
  {
    accessorKey: 'lastName',
    header: 'Last Name',
  },
  {
    accessorKey: 'email',
    header: 'Email',
  },
  {
    accessorKey: 'age',
    header: 'Age',
    size: 80,
  },
  {
    accessorKey: 'department',
    header: 'Department',
  },
  {
    accessorKey: 'salary',
    header: 'Salary',
    cell: (info) => `$${info.getValue().toLocaleString()}`,
  },
  {
    accessorKey: 'startDate',
    header: 'Start Date',
    cell: (info) => new Date(info.getValue()).toLocaleDateString(),
  },
  {
    accessorKey: 'status',
    header: 'Status',
    cell: (info) => (
      <span className={`status ${info.getValue().toLowerCase()}`}>{info.getValue()}</span>
    ),
  },
];

// Sample data
export const sampleData = [
  {
    id: 1,
    firstName: 'John',
    lastName: 'Doe',
    email: 'john.doe@company.com',
    age: 32,
    department: 'Engineering',
    salary: 85000,
    startDate: '2020-03-15',
    status: 'Active',
  },
  {
    id: 2,
    firstName: 'Jane',
    lastName: 'Smith',
    email: 'jane.smith@company.com',
    age: 28,
    department: 'Marketing',
    salary: 72000,
    startDate: '2021-06-22',
    status: 'Active',
  },
  {
    id: 3,
    firstName: 'Robert',
    lastName: 'Johnson',
    email: 'robert.j@company.com',
    age: 45,
    department: 'Sales',
    salary: 95000,
    startDate: '2018-11-05',
    status: 'Active',
  },
  {
    id: 4,
    firstName: 'Sarah',
    lastName: 'Wilson',
    email: 'sarah.wilson@company.com',
    age: 29,
    department: 'Engineering',
    salary: 88000,
    startDate: '2022-01-30',
    status: 'On Leave',
  },
  {
    id: 5,
    firstName: 'Michael',
    lastName: 'Brown',
    email: 'michael.b@company.com',
    age: 35,
    department: 'HR',
    salary: 68000,
    startDate: '2019-08-14',
    status: 'Active',
  },
  {
    id: 6,
    firstName: 'Emily',
    lastName: 'Davis',
    email: 'emily.davis@company.com',
    age: 26,
    department: 'Design',
    salary: 75000,
    startDate: '2023-02-18',
    status: 'Active',
  },
  {
    id: 7,
    firstName: 'David',
    lastName: 'Miller',
    email: 'david.m@company.com',
    age: 41,
    department: 'Engineering',
    salary: 110000,
    startDate: '2017-05-09',
    status: 'Active',
  },
  {
    id: 8,
    firstName: 'Lisa',
    lastName: 'Anderson',
    email: 'lisa.a@company.com',
    age: 31,
    department: 'Marketing',
    salary: 78000,
    startDate: '2020-09-12',
    status: 'On Leave',
  },
  {
    id: 9,
    firstName: 'James',
    lastName: 'Taylor',
    email: 'james.t@company.com',
    age: 38,
    department: 'Sales',
    salary: 89000,
    startDate: '2018-03-25',
    status: 'Active',
  },
  {
    id: 10,
    firstName: 'Amanda',
    lastName: 'Thomas',
    email: 'amanda.t@company.com',
    age: 27,
    department: 'Design',
    salary: 71000,
    startDate: '2022-07-08',
    status: 'Active',
  },
  {
    id: 11,
    firstName: 'Christopher',
    lastName: 'Lee',
    email: 'chris.lee@company.com',
    age: 33,
    department: 'Engineering',
    salary: 92000,
    startDate: '2019-12-01',
    status: 'Active',
  },
  {
    id: 12,
    firstName: 'Jennifer',
    lastName: 'Harris',
    email: 'jennifer.h@company.com',
    age: 29,
    department: 'HR',
    salary: 65000,
    startDate: '2021-04-19',
    status: 'Terminated',
  },
  {
    id: 13,
    firstName: 'Daniel',
    lastName: 'Martin',
    email: 'daniel.m@company.com',
    age: 42,
    department: 'Sales',
    salary: 102000,
    startDate: '2016-08-22',
    status: 'Active',
  },
  {
    id: 14,
    firstName: 'Maria',
    lastName: 'Garcia',
    email: 'maria.g@company.com',
    age: 36,
    department: 'Engineering',
    salary: 97000,
    startDate: '2018-10-15',
    status: 'Active',
  },
  {
    id: 15,
    firstName: 'Kevin',
    lastName: 'Clark',
    email: 'kevin.c@company.com',
    age: 30,
    department: 'Marketing',
    salary: 73000,
    startDate: '2023-01-05',
    status: 'Active',
  },
];
